name: EchoLearn CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint --if-present
    
    - name: Run tests
      run: npm test --if-present
    
    - name: Check for security vulnerabilities
      run: npm audit --audit-level moderate
    
    - name: Build application
      run: npm run build --if-present

  accessibility-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Start server
      run: |
        npm start &
        sleep 10
      env:
        NODE_ENV: test
    
    - name: Run accessibility tests
      run: |
        npx @axe-core/cli http://localhost:3000 --exit
      continue-on-error: true
    
    - name: Stop server
      run: pkill -f "node server.js" || true

  deploy:
    needs: [test, accessibility-check]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to production
      run: echo "Deploy to your preferred platform (AWS, Heroku, etc.)"
      # Add your deployment steps here